- name: nignx | commands
  shell: "{{ item }}"
  with_items:
    - sudo apt-get install -y dirmngr gnupg
    - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7
    - sudo apt-get install -y apt-transport-https ca-certificates
    - sudo sh -c 'echo deb https://oss-binaries.phusionpassenger.com/apt/passenger xenial main > /etc/apt/sources.list.d/passenger.list'
    - sudo apt-get update
    - sudo apt-get install -y nginx-extras passenger

- name: nginx | template nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0640
    owner: root
    group: root
  become: true

- name: nginx | template default
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
    mode: 0640
    owner: root
    group: root
  become: true

- name: nginx | restart
  service:
    name: nginx
    state: restarted
  become: true
  ignore_errors: true