- name: Redis | add apt repo
  apt_repository:
    repo: ppa:cartodb/redis-next
    state: present
  become: true

- name: Redis | Install packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - redis
  become: true

- name: Redis | service redis
  systemd: 
    state: started 
    name: redis-server 
    daemon_reload: yes
    enabled: true
  become: true

- name: Redis | service enable
  shell: systemctl enable redis-server
  become: true